exitAndEntryKey:
  appId: xf002
  appSecret: ydnxi7d82mf
  interface_prefix: http://wx.bzztc.gdbnet.cn
# exitAndEntryKey:
#   appId: xf002
#   appSecret: cefi1hb3jt4
#   interface_prefix: http://ems.xfxg.cn/_dev
foundedKey:
  accesseId: apifordcjt
  secretKey: password%110
  interface_prefix: http://ga.sczwfw.gov.cn
  convenienceServicesKey: # 公安便民服务对外接口密匙(创立提供)
    applyId: "100100"
    secretKey: n0venvfp3ghxp5vxm4qb7lua5g0foy0m

messageKey:
  appid: 1400070848
  appKey: 01fb2e2d383e40b85d565fd6ee027bd2
  verificationCode:
    templateId: 261599
    smsSign: 大成均图
whz:
  interface_prefix: https://whz.chinapopin.com/cdwhz

# 四川省印章查询地址
sealSelectUri: http://gayd.sczwfw.gov.cn:8923

# 用户token前缀
userTokenPrefix: userToken_
userLoginExists: 259200
onlineUser: ONLINE_USER

# 文件访问ip
fileUploadPrefix: http://114.116.21.95:20019

serverIp: 114.116.21.95

# EMS邮政快递（测试）
ems:
  authorization: 408a6c32e61d3ad5cb5c4e0cb3d2b089
  appkey: 8bd10fea96a9343253009a00ea312207
  appSecret: 45a9fdfbea2b22d8cbdf559f419d69ba
  path: http://60.205.8.187:18001/api/gateway
  version: V3.01
  interfaces:
    expressStatus: ems.inland.trace.query

# 微户政获取城市公安列表（。。。）
whzGetOpenCities: https://chinapopin.com/rkw-whz/api/whz-business/get-open-cities
whzGetChirdCities: https://chinapopin.com/lswhz-test/api/dept/get-all-dept
