swagger: "2.0"
info:
  description: "上传接口"
  version: "1.0.0"
  title: "上传接口"
# host: "127.0.0.1:20001"
# host: "114.116.21.95:20001"
basePath: "/wx"
# externalDocs:
#   description: "Find out more about Swagger"
#   url: "http://swagger.io"
tags:
- name: "upload"
  description: "上传接口"
  externalDocs:
    description: "上传接口"
schemes:
- "http"
- "https"
paths:
  /upload/upload:
    post:
      tags:
      - "upload"
      summary: 上传图片
      description: 上传图片
      consumes:
        - multipart/form-data
      parameters:
      - name: securityVerification
        in: header
        default: dalgurak 
        type: string
        description: 文档调试专用header参数，实际请求不需要此参数
      - name: body
        in: body
        type: object
        properties:
          userToken:
            type: string
          files:
            type: object
      produces:
      - "application/json"
      responses:
        200:
          description: "success"