swagger: "2.0"
info:
  description: "安全接口"
  version: "1.0.0"
  title: "安全接口"
# host: "114.116.21.95:20001"
basePath: "/wx"
# externalDocs:
#   description: "Find out more about Swagger"
#   url: "http://swagger.io"
tags:
- name: "sms"
  description: "短信接口"
  externalDocs:
    description: "短信接口"
- name: other
  description: other
schemes:
- "http"
- "https"
paths:
  /security/getSmsCode:
    post:
      tags:
      - "sms"
      # deprecated: true
      summary: "获取短信验证码"
      description: 获取短信验证码
      parameters:
      - name: securityVerification
        in: header
        default: dalgurak 
        type: string
        description: 文档调试专用header参数，实际请求不需要此参数
      - name: body
        in: body
        type: string
        properties:
          phoneNumber:
            type: string
        description: 电话号码
      produces:
      - "application/json"
      responses:
        200:
          description: "success"
  /security/clause:
    get:
      tags:
      - "other"
      summary: 获取小程序注册条款信息
      description: 获取小程序注册条款信息
      produces:
      - "application/json"
      responses:
        200:
          description: "success"
  /security/authentication/realPeopleCertification:
    post:
      tags:
      - "other"
      summary: 实人认证（负载）
      description: 实人认证（负载）
      produces:
      - "application/json"
      parameters:
      - name: securityVerification
        in: header
        default: dalgurak 
        type: string
        description: 文档调试专用header参数，实际请求不需要此参数
      - name: param
        in: body
        type: object
        description: 参数
      responses:
        200:
          description: "success"
  /security/authentication/getRealPeopleCertificationInfo:
    get:
      tags:
      - "other"
      summary: 获取用户的认证信息
      description: 获取用户的认证信息
      parameters:
      - name: phoneNumber
        in: query
        type: string
        description: 手机号码
      produces:
      - "application/json"
      responses:
        200:
          description: "success"
  /security/server/serverStatus:
    get:
      tags:
      - "other"
      summary: 获取服务器信息及其第三方接口信息
      description: 获取服务器信息及其第三方接口信息
      produces:
      - "application/json"
      responses:
        200:
          description: "success"